#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 16 16:28:42 2022

@author: cmr1
"""
#converter

f = open("collected.fasta","r")
out = open("noseqs.fasta","w")

for line in f:
    if line[0] == '>':
        out.write(line)
    else:
        continue
